name: Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'what version to release'
        required: true 
        type: string

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0
          ref: ${{ 'main' }}
      - name: Use Node.js v16
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: 16
          cache: yarn
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build
        run: yarn build
      - name: Bump Version & Publish
        run: |
          echo -e "\n# Bump the version"

          git config --global user.name 'DanCodes'
          git config --global user.email 'dan@dancodes.online'

          yarn standard-version -r ${{ inputs.version }} 

          git push --follow-tags origin main && yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
