name: Continuous Delivery

on:
  push:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'package.json'
    branches:
      - main

jobs:
  publish:
    name: Publish Next to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch || 'main' }}
      - name: Add TypeScript Problem Matcher
        run: echo "::add-matcher::.github/problemMatchers/tsc.json"
      - name: Use Node.js v16
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: 16
          cache: yarn
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Bump Version & Publish
        run: |
          echo -e "\n# Bump the version"

          git config --global user.name 'DanCodes'
          git config --global user.email 'dan@dancodes.online'

          yarn standard-version --skip.tag

          yarn release

          git commit -m "chore(npm): bump and release"
          git push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
